name: Bun - Playwright Tests, Chromium, Firefox, Webkit
on:
  workflow_call:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: 📥 Download deps
        run: |
          bun install
      - name: Install Playwright Browsers
        run: bun playwright install --with-deps chromium firefox webkit
      - name: Run Playwright tests
        run: bun playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
