name: Bun - Publish Node.js Package from Release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry_run:
        required: false
        type: boolean
    secrets:
      node_auth_token:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Apply Version
        run: npm --no-git-tag-version version ${{ inputs.version }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📥 Download deps
        run: bun install
      - name: Build
        run: |
          bun run build
        env:
          CI: true

      - name: Publish (DRY RUN MODE)
        run: bun publish --access public --dry-run
        if: ${{ inputs.dry_run }}
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.node_auth_token }}

      - name: Publish
        run: bun publish --access public
        if: ${{ !inputs.dry_run }}
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.node_auth_token }}
